In [1]:
import pandas as pd
import os 
import numpy as np
import re
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta

pd.options.mode.chained_assignment = None  # default='warn'

In [2]:
# Change directory
directory = os. chdir("C:/Users/Gi Han/OneDrive - Singapore Management University/Documents/GitHub/job-posting-analysis/data/MonsterSg")
files = os.listdir(".")
files

['Cloud Computing_Links_MonsterSg.csv',
 'Cloud Computing_MonsterSg_0-100.csv',
 'Cloud Computing_MonsterSg_1101-1300.csv',
 'Cloud Computing_MonsterSg_301-500.csv',
 'Cloud Computing_MonsterSg_501-700.csv',
 'Cloud Computing_MonsterSg_701-900.csv',
 'Cloud_Links_MonsterSg.csv',
 'Cloud_MonsterSg_0-1199.csv',
 'Cloud_MonsterSg_1200-1500.csv',
 'Cloud_MonsterSg_1501-2399.csv',
 'Cloud_MonsterSg_2400-2971.csv',
 'Cloud_MonsterSg_2971-3599.csv',
 'Cloud_MonsterSg_3600-4799.csv',
 'Cloud_MonsterSg_4800-6000.csv',
 'Cloud_MonsterSg_6000-8259.csv',
 'Posts_MonsterSg_header.csv']

In [86]:
# get all relevant files in df
# Change filename

relevant_csv = [x for x in files if 'Cloud Computing_MonsterSg' in x]
relevant_csv

['Cloud Computing_MonsterSg_0-100.csv',
 'Cloud Computing_MonsterSg_1101-1300.csv',
 'Cloud Computing_MonsterSg_301-500.csv',
 'Cloud Computing_MonsterSg_501-700.csv',
 'Cloud Computing_MonsterSg_701-900.csv']

In [87]:
# Combine all csv
df = pd.concat(map(pd.read_csv, relevant_csv), ignore_index=True, axis=0)
df

,job_title,company,salary,job_type,years_experience,tech_stack,job_description,industry,function,roles,last_updated,posted_on
0,Full-stack Tech Lead,Sygnum Pte. Ltd.,108000-144000 SGD Per Annum,Permanent Job,10-15 Years,Git It Operations Management Asset Managemen...,Sygnum Singapore is a digital asset-focused fu...,Other,IT,Other Software/Hardware/EDP,14-03-2022,3 days ago
1,Presales Solution Architect,Wiz Technologies (s) Pte. Ltd.,48000-96000 SGD Per Annum,Permanent Job,2-5 Years,Cloud Computing Vmware Networking Windows ...,This position reports to Operation Director of...,Other,IT,Other Software/Hardware/EDP,14-03-2022,4 days ago
2,Application Support Engineer - Ref: YC,A-it Software Services Pte Ltd,48000-90000 SGD Per Annum,Permanent Job,2-5 Years,Cloud Computing Devops Citrix AWS Release ...,We are looking for a DevOps Support Engineer a...,Other,IT,Other Software/Hardware/EDP,15-03-2022,a day ago
3,Cloud Engineer (Automation),Recruit Expert Pte. Ltd.,48000-60000 SGD Per Annum,Permanent Job,2-5 Years,Puppet Cloud Applications Cloud Security Cl...,"In-charge of the design, deployment, installat...",Other,IT,Other Software/Hardware/EDP,14-03-2022,a day ago
4,Cloud Engineer,Itconnectus Pte. Ltd.,60000-96000 SGD Per Annum,Permanent Job,2-5 Years,Kubernetes Azure Cloud Computing Scripting ...,Job Descriptions:\r\nExperienced AWS Cloud Adm...,Other,IT,Other Software/Hardware/EDP,14-03-2022,3 days ago
...,...,...,...,...,...,...,...,...,...,...,...,...
1394,Senior Program Manager,Amazon,Not Specified,Permanent Job,5-8 Years,NaN,DESCRIPTION\r\n\r\nJob summary\r\nAmazon has a...,Internet/E-commerce,IT,Project Leader/Project Manager,NaN,a month ago
1395,"Risk Specialist / Manager- Technology, Informa...",Bank of Singapore,Not Specified,Permanent Job,5-8 Years,NaN,GENERAL DESCRIPTION\r\nResponsible for second ...,Other,IT,Software Engineer/Programmer,NaN,3 days ago
1396,Innovation Solution Engineer,Oversea-chinese Banking Corporation Limited,Not Specified,Permanent Job,10-13 Years,NaN,Job Description :\r\n\r\nJob Summary:\r\nTo de...,Banking/Accounting/Financial Services,IT,Software Engineer/Programmer,NaN,6 days ago
1397,"Principal Engineer, SRE",Grabtaxi holdings pte ltd,Not Specified,Permanent Job,3-6 Years,Principal Engineer SRE,Get to know our Team:\r\nThe Systems & Operati...,Courier/Freight/Transportation,"IT , Engineering - Environmental/Health/Safety...",Software Engineer/Programmer,NaN,a day ago
1398,Account Manager -ICT /IT Solutions,Randstad,54000-84000 SGD Per Annum,Permanent Job,3-6 Years,Diploma,job details\r\n\r\nAbout my client\r\nA leadin...,Recruitment/Staffing/RPO,IT,Business Development Manager,NaN,7 days ago

In [88]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1399 entries, 0 to 1398
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   job_title         1399 non-null   object
 1   company           1399 non-null   object
 2   salary            1375 non-null   object
 3   job_type          1373 non-null   object
 4   years_experience  1375 non-null   object
 5   tech_stack        1051 non-null   object
 6   job_description   1373 non-null   object
 7   industry          1373 non-null   object
 8   function          1373 non-null   object
 9   roles             1279 non-null   object
 10  last_updated      885 non-null    object
 11  posted_on         1373 non-null   object
dtypes: object(12)
memory usage: 131.3+ KB

# Drop NA
Happens when: 
1. As Monster may direct users to the job posting in the company's website, the website format is different from Monster. 
Hence, data could not be scrapped for those job posting.
2. Usually if the salary is "Not specified" and years_experience is "undefined-undefined Years", the other fields will be NaN

In [89]:
# Drop job postings that are not from Monster
df.dropna(thresh=3, inplace=True)

In [90]:
# salary and years_exp are empty
df = df[(df['salary'] != 'Not Specified') | (df['years_experience'] != 'undefined-undefined Years')]
df

,job_title,company,salary,job_type,years_experience,tech_stack,job_description,industry,function,roles,last_updated,posted_on
0,Full-stack Tech Lead,Sygnum Pte. Ltd.,108000-144000 SGD Per Annum,Permanent Job,10-15 Years,Git It Operations Management Asset Managemen...,Sygnum Singapore is a digital asset-focused fu...,Other,IT,Other Software/Hardware/EDP,14-03-2022,3 days ago
1,Presales Solution Architect,Wiz Technologies (s) Pte. Ltd.,48000-96000 SGD Per Annum,Permanent Job,2-5 Years,Cloud Computing Vmware Networking Windows ...,This position reports to Operation Director of...,Other,IT,Other Software/Hardware/EDP,14-03-2022,4 days ago
2,Application Support Engineer - Ref: YC,A-it Software Services Pte Ltd,48000-90000 SGD Per Annum,Permanent Job,2-5 Years,Cloud Computing Devops Citrix AWS Release ...,We are looking for a DevOps Support Engineer a...,Other,IT,Other Software/Hardware/EDP,15-03-2022,a day ago
3,Cloud Engineer (Automation),Recruit Expert Pte. Ltd.,48000-60000 SGD Per Annum,Permanent Job,2-5 Years,Puppet Cloud Applications Cloud Security Cl...,"In-charge of the design, deployment, installat...",Other,IT,Other Software/Hardware/EDP,14-03-2022,a day ago
4,Cloud Engineer,Itconnectus Pte. Ltd.,60000-96000 SGD Per Annum,Permanent Job,2-5 Years,Kubernetes Azure Cloud Computing Scripting ...,Job Descriptions:\r\nExperienced AWS Cloud Adm...,Other,IT,Other Software/Hardware/EDP,14-03-2022,3 days ago
...,...,...,...,...,...,...,...,...,...,...,...,...
1394,Senior Program Manager,Amazon,Not Specified,Permanent Job,5-8 Years,NaN,DESCRIPTION\r\n\r\nJob summary\r\nAmazon has a...,Internet/E-commerce,IT,Project Leader/Project Manager,NaN,a month ago
1395,"Risk Specialist / Manager- Technology, Informa...",Bank of Singapore,Not Specified,Permanent Job,5-8 Years,NaN,GENERAL DESCRIPTION\r\nResponsible for second ...,Other,IT,Software Engineer/Programmer,NaN,3 days ago
1396,Innovation Solution Engineer,Oversea-chinese Banking Corporation Limited,Not Specified,Permanent Job,10-13 Years,NaN,Job Description :\r\n\r\nJob Summary:\r\nTo de...,Banking/Accounting/Financial Services,IT,Software Engineer/Programmer,NaN,6 days ago
1397,"Principal Engineer, SRE",Grabtaxi holdings pte ltd,Not Specified,Permanent Job,3-6 Years,Principal Engineer SRE,Get to know our Team:\r\nThe Systems & Operati...,Courier/Freight/Transportation,"IT , Engineering - Environmental/Health/Safety...",Software Engineer/Programmer,NaN,a day ago
1398,Account Manager -ICT /IT Solutions,Randstad,54000-84000 SGD Per Annum,Permanent Job,3-6 Years,Diploma,job details\r\n\r\nAbout my client\r\nA leadin...,Recruitment/Staffing/RPO,IT,Business Development Manager,NaN,7 days ago

# Date Posted

In [91]:
df['posted_on'].unique()

array(['3 days ago', '4 days ago', 'a day ago', '2 days ago',
       '5 days ago', '6 days ago', '7 days ago', '8 days ago',
       '9 days ago', '10 days ago', '11 days ago', '12 days ago',
       '13 days ago', '14 days ago', '15 days ago', '9 hours ago',
       '16 hours ago', '19 hours ago', '16 days ago', '18 days ago',
       '19 days ago', '20 days ago', '21 days ago', '22 days ago',
       '23 days ago', '17 days ago', '24 days ago', '25 days ago',
       'a month ago', '8 hours ago', '30+ days ago'], dtype=object)

In [92]:
# check rows with posted_on as nan
df[df['posted_on'].isna()]

Empty DataFrame
Columns: [job_title, company, salary, job_type, years_experience, tech_stack, job_description, industry, function, roles, last_updated, posted_on]
Index: []

In [60]:
# If rows do not contain much info, drop the row

# df.drop(7503, inplace=True)

### Difference between 30+ days ago and a month ago 
Since they are similar, we consider 30+ days ago as a month ago

In [ ]:
# df[df['posted_on'] == '30+ days ago']['last_updated'].value_counts()

In [ ]:
# df[df['posted_on'] == 'a month ago']['last_updated'].value_counts()

## Format date

In [93]:
# Standardise format to YYYY-MM-DD
def clean_last_updated(text):
    
    if '-' in text:
        date = datetime.strptime(text, '%d-%m-%Y')
        return date.strftime('%Y-%m-%d')
    
    elif '/' in text: 
        date = datetime.strptime(text, '%d/%m/%Y')
        return date.strftime('%Y-%m-%d')
    
    else:
        return np.nan  # no last updated date

In [94]:
def getDatePosted(text, date_of_scraping):
    """Converts date posted in the format of xx hours/days/months ago into datetime format

    Args:
        text (str): text in format: xx hours/days/months ago
        date_of_scraping (str): date in format 'YYYY-MM-DD'

    Returns:
        str: date in format 'YYYY-MM-DD' after subtracting the stated period 
    """

    # First convert the input text to datetime data type
    date_of_scraping = datetime.strptime(date_of_scraping, '%Y-%m-%d')
    date_posted = ''

    if "hour" in text or "a day" in text:
        # Automatically take the day before day of scraping (assume hours do not spill over to the day before)
        date = date_of_scraping + timedelta(days=-1) 
        date_posted = date.strftime('%Y-%m-%d')

    elif "30+ days" in text or "a month" in text:
        date = date_of_scraping + relativedelta(months=-1)
        date_posted = date.strftime('%Y-%m-%d')     
        
    elif "day" in text:
        # Extract number from text
        n_days = int(text.split()[0])
        date = date_of_scraping + timedelta(days=-n_days)
        date_posted = date.strftime('%Y-%m-%d')
        
    elif "month" in text:
        # Extract number from text
        n_months = int(text.split()[1])
        date = date_of_scraping + relativedelta(months=-n_months)
        date_posted = date.strftime('%Y-%m-%d')   

    return date_posted

In [95]:
# if last_updated is scrapped
df['date_posted'] = df['last_updated'].apply(lambda x: clean_last_updated(str(x)))
df.reset_index(inplace=True, drop=True)

In [96]:
# if last_updated is NOT scrapped
date_of_scraping = "2022-03-19"
for i in df[df['date_posted'].isna()].index:
    date_posted = getDatePosted(df.iloc[i]['posted_on'], date_of_scraping)
    df.iloc[i]['date_posted'] = date_posted

In [97]:
#  Drop posted_on and date_posted
df.drop(columns=['last_updated', 'posted_on'], inplace=True)
df

,job_title,company,salary,job_type,years_experience,tech_stack,job_description,industry,function,roles,date_posted
0,Full-stack Tech Lead,Sygnum Pte. Ltd.,108000-144000 SGD Per Annum,Permanent Job,10-15 Years,Git It Operations Management Asset Managemen...,Sygnum Singapore is a digital asset-focused fu...,Other,IT,Other Software/Hardware/EDP,2022-03-14
1,Presales Solution Architect,Wiz Technologies (s) Pte. Ltd.,48000-96000 SGD Per Annum,Permanent Job,2-5 Years,Cloud Computing Vmware Networking Windows ...,This position reports to Operation Director of...,Other,IT,Other Software/Hardware/EDP,2022-03-14
2,Application Support Engineer - Ref: YC,A-it Software Services Pte Ltd,48000-90000 SGD Per Annum,Permanent Job,2-5 Years,Cloud Computing Devops Citrix AWS Release ...,We are looking for a DevOps Support Engineer a...,Other,IT,Other Software/Hardware/EDP,2022-03-15
3,Cloud Engineer (Automation),Recruit Expert Pte. Ltd.,48000-60000 SGD Per Annum,Permanent Job,2-5 Years,Puppet Cloud Applications Cloud Security Cl...,"In-charge of the design, deployment, installat...",Other,IT,Other Software/Hardware/EDP,2022-03-14
4,Cloud Engineer,Itconnectus Pte. Ltd.,60000-96000 SGD Per Annum,Permanent Job,2-5 Years,Kubernetes Azure Cloud Computing Scripting ...,Job Descriptions:\r\nExperienced AWS Cloud Adm...,Other,IT,Other Software/Hardware/EDP,2022-03-14
...,...,...,...,...,...,...,...,...,...,...,...
1368,Senior Program Manager,Amazon,Not Specified,Permanent Job,5-8 Years,NaN,DESCRIPTION\r\n\r\nJob summary\r\nAmazon has a...,Internet/E-commerce,IT,Project Leader/Project Manager,2022-02-19
1369,"Risk Specialist / Manager- Technology, Informa...",Bank of Singapore,Not Specified,Permanent Job,5-8 Years,NaN,GENERAL DESCRIPTION\r\nResponsible for second ...,Other,IT,Software Engineer/Programmer,2022-03-16
1370,Innovation Solution Engineer,Oversea-chinese Banking Corporation Limited,Not Specified,Permanent Job,10-13 Years,NaN,Job Description :\r\n\r\nJob Summary:\r\nTo de...,Banking/Accounting/Financial Services,IT,Software Engineer/Programmer,2022-03-13
1371,"Principal Engineer, SRE",Grabtaxi holdings pte ltd,Not Specified,Permanent Job,3-6 Years,Principal Engineer SRE,Get to know our Team:\r\nThe Systems & Operati...,Courier/Freight/Transportation,"IT , Engineering - Environmental/Health/Safety...",Software Engineer/Programmer,2022-03-18
1372,Account Manager -ICT /IT Solutions,Randstad,54000-84000 SGD Per Annum,Permanent Job,3-6 Years,Diploma,job details\r\n\r\nAbout my client\r\nA leadin...,Recruitment/Staffing/RPO,IT,Business Development Manager,2022-03-12

## Remove duplicates
Companies may post the same job a few times over a period of time. We will take the first post

In [98]:
# sort according to date
df.sort_values(by="date_posted", inplace=True)

In [99]:
# drop duplicates 
df.drop_duplicates(subset=['job_title', 'company', 'job_description'], keep='first', inplace=True)
df.reset_index(inplace=True, drop=True)
df

,job_title,company,salary,job_type,years_experience,tech_stack,job_description,industry,function,roles,date_posted
0,Senior Python Developer,Citi,Not Specified,Permanent Job,Not Specified,NaN,Job Description :\r\n\r\nJob Purpose:\r\nWe ar...,Banking/Accounting/Financial Services,IT,Software Engineer/Programmer,2022-02-18
1,Senior Partner Solutions Architect (Microsoft),Amazon,Not Specified,Permanent Job,Not Specified,NaN,Job Description :\r\nJob summary\r\nDESCRIPTIO...,Internet/E-commerce,IT,Software Engineer/Programmer,2022-02-18
2,IT Technician,Ascend Com Pte. Ltd.,24000-36000 SGD Per Annum,Permanent Job,2-5 Years,Switches Mac Windows 10 Cloud Computing Wi...,Responsibilities:\r\nProvide helpdesk support ...,Other,IT,Other Software/Hardware/EDP,2022-02-19
3,Customer Engineer,Applied Materials South East Asia Pte. Ltd.,42000-84000 SGD Per Annum,Permanent Job,2-5 Years,Scalability Cloud Computing Google Cloud Pla...,Key Responsibilities\r\nPerforms all standard ...,Other,Manufacturing/Engineering/R&D,Other Production/Engineering/R&D,2022-02-19
4,Customer Engineering Manager,Applied Materials South East Asia Pte. Ltd.,78000-156000 SGD Per Annum,Permanent Job,2-5 Years,Cloud Computing Google Cloud Platform Softwa...,Key Responsibilities\r\nDevelops and maintains...,Other,Manufacturing/Engineering/R&D,Other Production/Engineering/R&D,2022-02-19
...,...,...,...,...,...,...,...,...,...,...,...
971,TDI - Production Support Engineer - Associate,Deutsche Bank,Not Specified,Permanent Job,2-5 Years,NaN,Position Overview\r\n\r\nDetails of the Divisi...,Banking/Accounting/Financial Services,"IT , Pharmaceutical/Biotechnology","Research Scientist , Clinical Trials Associate...",2022-03-18
972,Senior Consultant,Vmware,Not Specified,Permanent Job,Not Specified,NaN,The global VMware Professional Services Organi...,IT/Computers - Software,Health Care,Other Health Care/Hospitals,2022-03-18
973,Backend Lead Developer,Xylem Water Solutions Singapore Pte. Ltd.,84000-168000 SGD Per Annum,Permanent Job,7-10 Years,MongoDB Php Javascript Agile Methodology S...,The Backend Lead Developer will own and lead t...,Other,Manufacturing/Engineering/R&D,Other Production/Engineering/R&D,2022-03-18
974,"Data Scientist (Python, Machine Learning) - di...",Recruit Express Pte. Ltd,Not Specified,Permanent Job,Not Specified,IT Applications (Software / ERP),Job Description :\r\n\r\nperform data analysis...,Recruitment/Staffing/RPO,IT,Software Engineer/Programmer,2022-03-18
975,Project Manager,Techbridge Market Holdings Pte Ltd,Not Specified,Permanent Job,12-15 Years,NaN,Job Description :\r\n\r\nProject Manager\r\nLe...,Recruitment/Staffing/RPO,IT,Project Leader/Project Manager,2022-03-18

# Salary
Convert to list(int) --> [lower, upper]

In [18]:
# Check different types of data

# df['salary'].unique()

In [100]:
def clean_salary(text):        
    if text == 'Not Specified' or text == 'nan':
        return np.nan
    else: 
        text = re.sub("[a-zA-Z]", "", text)
        salary_range = text.strip().split('-')
        return salary_range

In [101]:
df['salary'] = df['salary'].apply(lambda x: clean_salary(str(x)))
df

,job_title,company,salary,job_type,years_experience,tech_stack,job_description,industry,function,roles,date_posted
0,Senior Python Developer,Citi,NaN,Permanent Job,Not Specified,NaN,Job Description :\r\n\r\nJob Purpose:\r\nWe ar...,Banking/Accounting/Financial Services,IT,Software Engineer/Programmer,2022-02-18
1,Senior Partner Solutions Architect (Microsoft),Amazon,NaN,Permanent Job,Not Specified,NaN,Job Description :\r\nJob summary\r\nDESCRIPTIO...,Internet/E-commerce,IT,Software Engineer/Programmer,2022-02-18
2,IT Technician,Ascend Com Pte. Ltd.,"[24000, 36000]",Permanent Job,2-5 Years,Switches Mac Windows 10 Cloud Computing Wi...,Responsibilities:\r\nProvide helpdesk support ...,Other,IT,Other Software/Hardware/EDP,2022-02-19
3,Customer Engineer,Applied Materials South East Asia Pte. Ltd.,"[42000, 84000]",Permanent Job,2-5 Years,Scalability Cloud Computing Google Cloud Pla...,Key Responsibilities\r\nPerforms all standard ...,Other,Manufacturing/Engineering/R&D,Other Production/Engineering/R&D,2022-02-19
4,Customer Engineering Manager,Applied Materials South East Asia Pte. Ltd.,"[78000, 156000]",Permanent Job,2-5 Years,Cloud Computing Google Cloud Platform Softwa...,Key Responsibilities\r\nDevelops and maintains...,Other,Manufacturing/Engineering/R&D,Other Production/Engineering/R&D,2022-02-19
...,...,...,...,...,...,...,...,...,...,...,...
971,TDI - Production Support Engineer - Associate,Deutsche Bank,NaN,Permanent Job,2-5 Years,NaN,Position Overview\r\n\r\nDetails of the Divisi...,Banking/Accounting/Financial Services,"IT , Pharmaceutical/Biotechnology","Research Scientist , Clinical Trials Associate...",2022-03-18
972,Senior Consultant,Vmware,NaN,Permanent Job,Not Specified,NaN,The global VMware Professional Services Organi...,IT/Computers - Software,Health Care,Other Health Care/Hospitals,2022-03-18
973,Backend Lead Developer,Xylem Water Solutions Singapore Pte. Ltd.,"[84000, 168000]",Permanent Job,7-10 Years,MongoDB Php Javascript Agile Methodology S...,The Backend Lead Developer will own and lead t...,Other,Manufacturing/Engineering/R&D,Other Production/Engineering/R&D,2022-03-18
974,"Data Scientist (Python, Machine Learning) - di...",Recruit Express Pte. Ltd,NaN,Permanent Job,Not Specified,IT Applications (Software / ERP),Job Description :\r\n\r\nperform data analysis...,Recruitment/Staffing/RPO,IT,Software Engineer/Programmer,2022-03-18
975,Project Manager,Techbridge Market Holdings Pte Ltd,NaN,Permanent Job,12-15 Years,NaN,Job Description :\r\n\r\nProject Manager\r\nLe...,Recruitment/Staffing/RPO,IT,Project Leader/Project Manager,2022-03-18

# Job Type

In [102]:
df['job_type'].unique()

array(['Permanent Job', 'Contract Job'], dtype=object)

In [103]:
# may need to change depending on the job types available in the platform
def clean_job_type(text):
    if 'permanent' in text.lower():
        return 'permanent'
    elif 'contract' in text.lower():
        return 'contract'
    elif 'intern' in text.lower():
        return 'intern'
    else: 
        return np.nan

In [104]:
df['job_type'] = df['job_type'].apply(lambda x: clean_job_type(str(x)))
df

,job_title,company,salary,job_type,years_experience,tech_stack,job_description,industry,function,roles,date_posted
0,Senior Python Developer,Citi,NaN,permanent,Not Specified,NaN,Job Description :\r\n\r\nJob Purpose:\r\nWe ar...,Banking/Accounting/Financial Services,IT,Software Engineer/Programmer,2022-02-18
1,Senior Partner Solutions Architect (Microsoft),Amazon,NaN,permanent,Not Specified,NaN,Job Description :\r\nJob summary\r\nDESCRIPTIO...,Internet/E-commerce,IT,Software Engineer/Programmer,2022-02-18
2,IT Technician,Ascend Com Pte. Ltd.,"[24000, 36000]",permanent,2-5 Years,Switches Mac Windows 10 Cloud Computing Wi...,Responsibilities:\r\nProvide helpdesk support ...,Other,IT,Other Software/Hardware/EDP,2022-02-19
3,Customer Engineer,Applied Materials South East Asia Pte. Ltd.,"[42000, 84000]",permanent,2-5 Years,Scalability Cloud Computing Google Cloud Pla...,Key Responsibilities\r\nPerforms all standard ...,Other,Manufacturing/Engineering/R&D,Other Production/Engineering/R&D,2022-02-19
4,Customer Engineering Manager,Applied Materials South East Asia Pte. Ltd.,"[78000, 156000]",permanent,2-5 Years,Cloud Computing Google Cloud Platform Softwa...,Key Responsibilities\r\nDevelops and maintains...,Other,Manufacturing/Engineering/R&D,Other Production/Engineering/R&D,2022-02-19
...,...,...,...,...,...,...,...,...,...,...,...
971,TDI - Production Support Engineer - Associate,Deutsche Bank,NaN,permanent,2-5 Years,NaN,Position Overview\r\n\r\nDetails of the Divisi...,Banking/Accounting/Financial Services,"IT , Pharmaceutical/Biotechnology","Research Scientist , Clinical Trials Associate...",2022-03-18
972,Senior Consultant,Vmware,NaN,permanent,Not Specified,NaN,The global VMware Professional Services Organi...,IT/Computers - Software,Health Care,Other Health Care/Hospitals,2022-03-18
973,Backend Lead Developer,Xylem Water Solutions Singapore Pte. Ltd.,"[84000, 168000]",permanent,7-10 Years,MongoDB Php Javascript Agile Methodology S...,The Backend Lead Developer will own and lead t...,Other,Manufacturing/Engineering/R&D,Other Production/Engineering/R&D,2022-03-18
974,"Data Scientist (Python, Machine Learning) - di...",Recruit Express Pte. Ltd,NaN,permanent,Not Specified,IT Applications (Software / ERP),Job Description :\r\n\r\nperform data analysis...,Recruitment/Staffing/RPO,IT,Software Engineer/Programmer,2022-03-18
975,Project Manager,Techbridge Market Holdings Pte Ltd,NaN,permanent,12-15 Years,NaN,Job Description :\r\n\r\nProject Manager\r\nLe...,Recruitment/Staffing/RPO,IT,Project Leader/Project Manager,2022-03-18

# Years of Experience
Convert to list(int) --> [lower, upper]

In [ ]:
# Check different types of data

# df['years_experience'].unique()

In [105]:
def clean_yr_exp(text):        
    if text == 'Not Specified' or text == 'nan':
        return np.nan
    elif text == 'Fresher':
        return [0,0]
    else: 
        text = text.split()[0]
        yr_exp_range = text.strip().split('-')
        return yr_exp_range

In [106]:
df['years_experience'] = df['years_experience'].apply(lambda x: clean_yr_exp(str(x)))
df

,job_title,company,salary,job_type,years_experience,tech_stack,job_description,industry,function,roles,date_posted
0,Senior Python Developer,Citi,NaN,permanent,NaN,NaN,Job Description :\r\n\r\nJob Purpose:\r\nWe ar...,Banking/Accounting/Financial Services,IT,Software Engineer/Programmer,2022-02-18
1,Senior Partner Solutions Architect (Microsoft),Amazon,NaN,permanent,NaN,NaN,Job Description :\r\nJob summary\r\nDESCRIPTIO...,Internet/E-commerce,IT,Software Engineer/Programmer,2022-02-18
2,IT Technician,Ascend Com Pte. Ltd.,"[24000, 36000]",permanent,"[2, 5]",Switches Mac Windows 10 Cloud Computing Wi...,Responsibilities:\r\nProvide helpdesk support ...,Other,IT,Other Software/Hardware/EDP,2022-02-19
3,Customer Engineer,Applied Materials South East Asia Pte. Ltd.,"[42000, 84000]",permanent,"[2, 5]",Scalability Cloud Computing Google Cloud Pla...,Key Responsibilities\r\nPerforms all standard ...,Other,Manufacturing/Engineering/R&D,Other Production/Engineering/R&D,2022-02-19
4,Customer Engineering Manager,Applied Materials South East Asia Pte. Ltd.,"[78000, 156000]",permanent,"[2, 5]",Cloud Computing Google Cloud Platform Softwa...,Key Responsibilities\r\nDevelops and maintains...,Other,Manufacturing/Engineering/R&D,Other Production/Engineering/R&D,2022-02-19
...,...,...,...,...,...,...,...,...,...,...,...
971,TDI - Production Support Engineer - Associate,Deutsche Bank,NaN,permanent,"[2, 5]",NaN,Position Overview\r\n\r\nDetails of the Divisi...,Banking/Accounting/Financial Services,"IT , Pharmaceutical/Biotechnology","Research Scientist , Clinical Trials Associate...",2022-03-18
972,Senior Consultant,Vmware,NaN,permanent,NaN,NaN,The global VMware Professional Services Organi...,IT/Computers - Software,Health Care,Other Health Care/Hospitals,2022-03-18
973,Backend Lead Developer,Xylem Water Solutions Singapore Pte. Ltd.,"[84000, 168000]",permanent,"[7, 10]",MongoDB Php Javascript Agile Methodology S...,The Backend Lead Developer will own and lead t...,Other,Manufacturing/Engineering/R&D,Other Production/Engineering/R&D,2022-03-18
974,"Data Scientist (Python, Machine Learning) - di...",Recruit Express Pte. Ltd,NaN,permanent,NaN,IT Applications (Software / ERP),Job Description :\r\n\r\nperform data analysis...,Recruitment/Staffing/RPO,IT,Software Engineer/Programmer,2022-03-18
975,Project Manager,Techbridge Market Holdings Pte Ltd,NaN,permanent,"[12, 15]",NaN,Job Description :\r\n\r\nProject Manager\r\nLe...,Recruitment/Staffing/RPO,IT,Project Leader/Project Manager,2022-03-18

# Tech Stack
Convert to list

In [ ]:
# Check different types of data

# df['tech_stack'][0]

In [107]:
def clean_tech_stack(text):
    if text == 'nan': 
        return np.nan
    else:
        return text.split('  ')

In [108]:
df['tech_stack'] = df['tech_stack'].apply(lambda x: clean_tech_stack(str(x)))
df

,job_title,company,salary,job_type,years_experience,tech_stack,job_description,industry,function,roles,date_posted
0,Senior Python Developer,Citi,NaN,permanent,NaN,NaN,Job Description :\r\n\r\nJob Purpose:\r\nWe ar...,Banking/Accounting/Financial Services,IT,Software Engineer/Programmer,2022-02-18
1,Senior Partner Solutions Architect (Microsoft),Amazon,NaN,permanent,NaN,NaN,Job Description :\r\nJob summary\r\nDESCRIPTIO...,Internet/E-commerce,IT,Software Engineer/Programmer,2022-02-18
2,IT Technician,Ascend Com Pte. Ltd.,"[24000, 36000]",permanent,"[2, 5]","[Switches, Mac, Windows 10, Cloud Computing, W...",Responsibilities:\r\nProvide helpdesk support ...,Other,IT,Other Software/Hardware/EDP,2022-02-19
3,Customer Engineer,Applied Materials South East Asia Pte. Ltd.,"[42000, 84000]",permanent,"[2, 5]","[Scalability, Cloud Computing, Google Cloud Pl...",Key Responsibilities\r\nPerforms all standard ...,Other,Manufacturing/Engineering/R&D,Other Production/Engineering/R&D,2022-02-19
4,Customer Engineering Manager,Applied Materials South East Asia Pte. Ltd.,"[78000, 156000]",permanent,"[2, 5]","[Cloud Computing, Google Cloud Platform, Softw...",Key Responsibilities\r\nDevelops and maintains...,Other,Manufacturing/Engineering/R&D,Other Production/Engineering/R&D,2022-02-19
...,...,...,...,...,...,...,...,...,...,...,...
971,TDI - Production Support Engineer - Associate,Deutsche Bank,NaN,permanent,"[2, 5]",NaN,Position Overview\r\n\r\nDetails of the Divisi...,Banking/Accounting/Financial Services,"IT , Pharmaceutical/Biotechnology","Research Scientist , Clinical Trials Associate...",2022-03-18
972,Senior Consultant,Vmware,NaN,permanent,NaN,NaN,The global VMware Professional Services Organi...,IT/Computers - Software,Health Care,Other Health Care/Hospitals,2022-03-18
973,Backend Lead Developer,Xylem Water Solutions Singapore Pte. Ltd.,"[84000, 168000]",permanent,"[7, 10]","[MongoDB, Php, Javascript, Agile Methodology, ...",The Backend Lead Developer will own and lead t...,Other,Manufacturing/Engineering/R&D,Other Production/Engineering/R&D,2022-03-18
974,"Data Scientist (Python, Machine Learning) - di...",Recruit Express Pte. Ltd,NaN,permanent,NaN,[IT Applications (Software / ERP) ],Job Description :\r\n\r\nperform data analysis...,Recruitment/Staffing/RPO,IT,Software Engineer/Programmer,2022-03-18
975,Project Manager,Techbridge Market Holdings Pte Ltd,NaN,permanent,"[12, 15]",NaN,Job Description :\r\n\r\nProject Manager\r\nLe...,Recruitment/Staffing/RPO,IT,Project Leader/Project Manager,2022-03-18

# Industry& functions
Convert to list

In [ ]:
# df['industry'].unique()

In [ ]:
# df['function'].unique()

In [109]:
def str_to_list(text):
    if text == 'nan': 
        return np.nan
    else:
        return text.split(' , ')

In [110]:
df['industry'] = df['industry'].apply(lambda x: str_to_list(str(x)))
df['function'] = df['function'].apply(lambda x: str_to_list(str(x)))

In [111]:
df

,job_title,company,salary,job_type,years_experience,tech_stack,job_description,industry,function,roles,date_posted
0,Senior Python Developer,Citi,NaN,permanent,NaN,NaN,Job Description :\r\n\r\nJob Purpose:\r\nWe ar...,[Banking/Accounting/Financial Services],[IT],Software Engineer/Programmer,2022-02-18
1,Senior Partner Solutions Architect (Microsoft),Amazon,NaN,permanent,NaN,NaN,Job Description :\r\nJob summary\r\nDESCRIPTIO...,[Internet/E-commerce],[IT],Software Engineer/Programmer,2022-02-18
2,IT Technician,Ascend Com Pte. Ltd.,"[24000, 36000]",permanent,"[2, 5]","[Switches, Mac, Windows 10, Cloud Computing, W...",Responsibilities:\r\nProvide helpdesk support ...,[Other],[IT],Other Software/Hardware/EDP,2022-02-19
3,Customer Engineer,Applied Materials South East Asia Pte. Ltd.,"[42000, 84000]",permanent,"[2, 5]","[Scalability, Cloud Computing, Google Cloud Pl...",Key Responsibilities\r\nPerforms all standard ...,[Other],[Manufacturing/Engineering/R&D],Other Production/Engineering/R&D,2022-02-19
4,Customer Engineering Manager,Applied Materials South East Asia Pte. Ltd.,"[78000, 156000]",permanent,"[2, 5]","[Cloud Computing, Google Cloud Platform, Softw...",Key Responsibilities\r\nDevelops and maintains...,[Other],[Manufacturing/Engineering/R&D],Other Production/Engineering/R&D,2022-02-19
...,...,...,...,...,...,...,...,...,...,...,...
971,TDI - Production Support Engineer - Associate,Deutsche Bank,NaN,permanent,"[2, 5]",NaN,Position Overview\r\n\r\nDetails of the Divisi...,[Banking/Accounting/Financial Services],"[IT, Pharmaceutical/Biotechnology]","Research Scientist , Clinical Trials Associate...",2022-03-18
972,Senior Consultant,Vmware,NaN,permanent,NaN,NaN,The global VMware Professional Services Organi...,[IT/Computers - Software],[Health Care],Other Health Care/Hospitals,2022-03-18
973,Backend Lead Developer,Xylem Water Solutions Singapore Pte. Ltd.,"[84000, 168000]",permanent,"[7, 10]","[MongoDB, Php, Javascript, Agile Methodology, ...",The Backend Lead Developer will own and lead t...,[Other],[Manufacturing/Engineering/R&D],Other Production/Engineering/R&D,2022-03-18
974,"Data Scientist (Python, Machine Learning) - di...",Recruit Express Pte. Ltd,NaN,permanent,NaN,[IT Applications (Software / ERP) ],Job Description :\r\n\r\nperform data analysis...,[Recruitment/Staffing/RPO],[IT],Software Engineer/Programmer,2022-03-18
975,Project Manager,Techbridge Market Holdings Pte Ltd,NaN,permanent,"[12, 15]",NaN,Job Description :\r\n\r\nProject Manager\r\nLe...,[Recruitment/Staffing/RPO],[IT],Project Leader/Project Manager,2022-03-18

# Roles
Convert to list

In [ ]:
# df['roles'].unique()

In [112]:
def clean_role(text):
    if '  ' in text: 
        return np.nan
    else: 
        return str_to_list(text)

In [113]:
df['roles'] = df['roles'].apply(lambda x: clean_role(str(x)))
df

,job_title,company,salary,job_type,years_experience,tech_stack,job_description,industry,function,roles,date_posted
0,Senior Python Developer,Citi,NaN,permanent,NaN,NaN,Job Description :\r\n\r\nJob Purpose:\r\nWe ar...,[Banking/Accounting/Financial Services],[IT],[Software Engineer/Programmer],2022-02-18
1,Senior Partner Solutions Architect (Microsoft),Amazon,NaN,permanent,NaN,NaN,Job Description :\r\nJob summary\r\nDESCRIPTIO...,[Internet/E-commerce],[IT],[Software Engineer/Programmer],2022-02-18
2,IT Technician,Ascend Com Pte. Ltd.,"[24000, 36000]",permanent,"[2, 5]","[Switches, Mac, Windows 10, Cloud Computing, W...",Responsibilities:\r\nProvide helpdesk support ...,[Other],[IT],[Other Software/Hardware/EDP],2022-02-19
3,Customer Engineer,Applied Materials South East Asia Pte. Ltd.,"[42000, 84000]",permanent,"[2, 5]","[Scalability, Cloud Computing, Google Cloud Pl...",Key Responsibilities\r\nPerforms all standard ...,[Other],[Manufacturing/Engineering/R&D],[Other Production/Engineering/R&D],2022-02-19
4,Customer Engineering Manager,Applied Materials South East Asia Pte. Ltd.,"[78000, 156000]",permanent,"[2, 5]","[Cloud Computing, Google Cloud Platform, Softw...",Key Responsibilities\r\nDevelops and maintains...,[Other],[Manufacturing/Engineering/R&D],[Other Production/Engineering/R&D],2022-02-19
...,...,...,...,...,...,...,...,...,...,...,...
971,TDI - Production Support Engineer - Associate,Deutsche Bank,NaN,permanent,"[2, 5]",NaN,Position Overview\r\n\r\nDetails of the Divisi...,[Banking/Accounting/Financial Services],"[IT, Pharmaceutical/Biotechnology]","[Research Scientist, Clinical Trials Associate...",2022-03-18
972,Senior Consultant,Vmware,NaN,permanent,NaN,NaN,The global VMware Professional Services Organi...,[IT/Computers - Software],[Health Care],[Other Health Care/Hospitals],2022-03-18
973,Backend Lead Developer,Xylem Water Solutions Singapore Pte. Ltd.,"[84000, 168000]",permanent,"[7, 10]","[MongoDB, Php, Javascript, Agile Methodology, ...",The Backend Lead Developer will own and lead t...,[Other],[Manufacturing/Engineering/R&D],[Other Production/Engineering/R&D],2022-03-18
974,"Data Scientist (Python, Machine Learning) - di...",Recruit Express Pte. Ltd,NaN,permanent,NaN,[IT Applications (Software / ERP) ],Job Description :\r\n\r\nperform data analysis...,[Recruitment/Staffing/RPO],[IT],[Software Engineer/Programmer],2022-03-18
975,Project Manager,Techbridge Market Holdings Pte Ltd,NaN,permanent,"[12, 15]",NaN,Job Description :\r\n\r\nProject Manager\r\nLe...,[Recruitment/Staffing/RPO],[IT],[Project Leader/Project Manager],2022-03-18

# Job Description (Not Done)

In [128]:
test = df['job_description'][100]
test.split('\r\n')

['Skillset',
 'At least 3 years of RPA development experience with proven track records of successful implementation.',
 'Strong knowledge on RPA development life cycle',
 'Independent developer and able to provide guidance to junior developers',
 'Hands-on experience in top RPA tools like Automation Anywhere, UiPath',
 'Kryon RPA advanced developer certified (preferred)',
 'Strong project management skill and development skill',
 'Scope',
 'Project manage end to end process development including junior developers processes (if any)',
 'As Independent developer and follow COE Coding standard',
 'To provide guidance to junior developers including but not limited to source code review.',
 'To design and provide best suit solutions to the business needs',
 'To support UAT and Post Prod verification',
 'To provide documentation as per COE framework and standard',
 'Ensure timing closure of defects',
 'Investigation and troubleshooting of Prod and UAT issue/defect.',
 'Highlighting any risk and issue to COE as earlier',
 'Perform adhoc task assigned by COE']

In [131]:
job_des = pd.DataFrame(data = df[df['job_description'].isna() == False]['job_description'])
job_des['description'] = 0
job_des['qualification'] = 0
job_des['requirement'] = 0
job_des['responsibilities'] = 0
job_des.reset_index(inplace=True, drop=True)

In [130]:
# number of postings with 'description', 'qualification', 'requirement', 'responsibilities'

for i, row in job_des.iterrows():    
        if 'description' in row['job_description'].lower():
            job_des['description'].iloc[i] = 1
        if 'qualification' in row['job_description'].lower():
            job_des['qualification'].iloc[i] = 1
        if 'requirement' in row['job_description'].lower():
            job_des['requirement'].iloc[i] = 1
        if 'responsibilities' in row['job_description'].lower():
            job_des['responsibilities'].iloc[i] = 1
            
job_des

,job_description,description,qualification,requirement,responsibilities
0,Job Description :\r\n\r\nJob Purpose:\r\nWe ar...,1,0,1,0
1,Job Description :\r\nJob summary\r\nDESCRIPTIO...,1,1,0,1
2,Responsibilities:\r\nProvide helpdesk support ...,0,0,1,1
3,Key Responsibilities\r\nPerforms all standard ...,0,0,0,1
4,Key Responsibilities\r\nDevelops and maintains...,0,0,0,1
...,...,...,...,...,...
971,Position Overview\r\n\r\nDetails of the Divisi...,0,0,1,1
972,The global VMware Professional Services Organi...,0,1,1,1
973,The Backend Lead Developer will own and lead t...,0,1,0,1
974,Job Description :\r\n\r\nperform data analysis...,1,0,1,0
975,Job Description :\r\n\r\nProject Manager\r\nLe...,1,1,1,0

In [ ]:
job_des['total'] = job_des['description'] + job_des['qualification'] + job_des['requirement'] + job_des['responsibilities']
job_des

# Final DataFrame
To be converted to csv

In [115]:
# Change filename
url_df = pd.read_csv('Cloud Computing_Links_MonsterSg.csv')
url_df.head()

,job_title,company,url
0,Full-stack Tech Lead,Sygnum Pte. Ltd.,https://www.monster.com.sg/seeker/job-details?...
1,Presales Solution Architect,Wiz Technologies (s) Pte. Ltd.,https://www.monster.com.sg/seeker/job-details?...
2,Application Support Engineer - Ref: YC,A-it Software Services Pte Ltd,https://www.monster.com.sg/seeker/job-details?...
3,Cloud Engineer (Automation),Recruit Expert Pte. Ltd.,https://www.monster.com.sg/seeker/job-details?...
4,Cloud Engineer,Itconnectus Pte. Ltd.,https://www.monster.com.sg/seeker/job-details?...

In [116]:
# Drop duplicated job_title and company
url_df.drop_duplicates(subset=['job_title', 'company'], inplace=True)
url_df

,job_title,company,url
0,Full-stack Tech Lead,Sygnum Pte. Ltd.,https://www.monster.com.sg/seeker/job-details?...
1,Presales Solution Architect,Wiz Technologies (s) Pte. Ltd.,https://www.monster.com.sg/seeker/job-details?...
2,Application Support Engineer - Ref: YC,A-it Software Services Pte Ltd,https://www.monster.com.sg/seeker/job-details?...
3,Cloud Engineer (Automation),Recruit Expert Pte. Ltd.,https://www.monster.com.sg/seeker/job-details?...
4,Cloud Engineer,Itconnectus Pte. Ltd.,https://www.monster.com.sg/seeker/job-details?...
...,...,...,...
1445,Software Engineer,WongPartnership LLP,https://www.monster.com.sg/seeker/job-details?...
1446,Information Technology Principal Trainer,PrimeStaff Management Services Pte Ltd,https://www.monster.com.sg/seeker/job-details?...
1447,Solution Architect-IT Cyber Security Cloud Com...,Infinite Computer Solutions Pte Ltd,https://www.monster.com.sg/seeker/job-details?...
1448,Cloud Senior Engineer,Infinite Computer Solutions Pte Ltd,https://www.monster.com.sg/seeker/job-details?...
1449,Technical Lead ( Java),Sciente International Pte Ltd,https://www.monster.com.sg/seeker/cjt/job-vaca...

In [117]:
final_df = df.merge(url_df, on=['job_title', 'company'])
final_df

,job_title,company,salary,job_type,years_experience,tech_stack,job_description,industry,function,roles,date_posted,url
0,Senior Python Developer,Citi,NaN,permanent,NaN,NaN,Job Description :\r\n\r\nJob Purpose:\r\nWe ar...,[Banking/Accounting/Financial Services],[IT],[Software Engineer/Programmer],2022-02-18,https://www.monster.com.sg/seeker/job-details?...
1,Senior Partner Solutions Architect (Microsoft),Amazon,NaN,permanent,NaN,NaN,Job Description :\r\nJob summary\r\nDESCRIPTIO...,[Internet/E-commerce],[IT],[Software Engineer/Programmer],2022-02-18,https://www.monster.com.sg/seeker/job-details?...
2,IT Technician,Ascend Com Pte. Ltd.,"[24000, 36000]",permanent,"[2, 5]","[Switches, Mac, Windows 10, Cloud Computing, W...",Responsibilities:\r\nProvide helpdesk support ...,[Other],[IT],[Other Software/Hardware/EDP],2022-02-19,https://www.monster.com.sg/seeker/job-details?...
3,Customer Engineer,Applied Materials South East Asia Pte. Ltd.,"[42000, 84000]",permanent,"[2, 5]","[Scalability, Cloud Computing, Google Cloud Pl...",Key Responsibilities\r\nPerforms all standard ...,[Other],[Manufacturing/Engineering/R&D],[Other Production/Engineering/R&D],2022-02-19,https://www.monster.com.sg/seeker/job-details?...
4,Customer Engineer,Applied Materials South East Asia Pte. Ltd.,"[46800, 93600]",permanent,"[2, 5]","[Scalability, Cloud Computing, Google Cloud Pl...",Has developed specialized skills or is multi-s...,[Other],[Manufacturing/Engineering/R&D],[Other Production/Engineering/R&D],2022-02-19,https://www.monster.com.sg/seeker/job-details?...
...,...,...,...,...,...,...,...,...,...,...,...,...
816,"Research Scientist, Bioinformatics",Hummingbird Bioscience Pte. Ltd.,"[78000, 114000]",permanent,"[2, 5]","[Machine Learning, Python, Data Science, Datab...",Opportunity to work at the cutting edge of dru...,[Other],[Manufacturing/Engineering/R&D],[Other Production/Engineering/R&D],2022-03-17,https://www.monster.com.sg/seeker/job-details?...
817,Data product owner - Chapter Lead,Dkatalis Private Limited,"[156000, 216000]",permanent,"[5, 7]","[Wireframes, Kubernetes, Scrum, User Stories, ...",Job specification\r\nThe Data Product Owner Ch...,[Other],"[IT, Banking]","[Product Manager - Auto/Home/Personal Loan, Ot...",2022-03-17,https://www.monster.com.sg/seeker/job-details?...
818,Network Engineer,Nera Telecommunications Ltd,"[36000, 66000]",permanent,"[2, 5]","[OSPF, Ccna, Data Center, DHCP, Information Te...",Nera Telecommunications Ltd (Nera) is a global...,[Other],[IT],[Other Software/Hardware/EDP],2022-03-17,https://www.monster.com.sg/seeker/job-details?...
819,"Principal Engineer, SRE",Grabtaxi holdings pte ltd,NaN,permanent,"[3, 6]","[Principal Engineer, SRE ]",Get to know our Team:\r\nThe Systems & Operati...,[Courier/Freight/Transportation],"[IT, Engineering - Environmental/Health/Safety...",[Software Engineer/Programmer],2022-03-18,https://www.monster.com.sg/seeker/job-details?...
820,Senior Consultant,Vmware,NaN,permanent,NaN,NaN,The global VMware Professional Services Organi...,[IT/Computers - Software],[Health Care],[Other Health Care/Hospitals],2022-03-18,https://www.monster.com.sg/seeker/job-details?...

In [118]:
# Change directory and filename
save_dir = "C:/Users/Gi Han/OneDrive - Singapore Management University/Documents/Y3T2/IS434 Social Analytics & Applications/Project/Cleaned Data"
final_df.to_csv(f'{save_dir}/Cloud Computing_MonsterSg.csv', index=False)

# Combine all data from Monster

In [124]:
os.chdir(save_dir)
save_files = os.listdir(".")
save_files

['Cloud Computing_MonsterSg.csv', 'Cloud_MonsterSg.csv']

In [125]:
all_df = pd.concat(map(pd.read_csv, save_files), ignore_index=True, axis=0)
all_df

,job_title,company,salary,job_type,years_experience,tech_stack,job_description,industry,function,roles,date_posted,url
0,Senior Python Developer,Citi,NaN,permanent,NaN,NaN,Job Description :\r\n\r\nJob Purpose:\r\nWe ar...,['Banking/Accounting/Financial Services'],['IT'],['Software Engineer/Programmer'],2022-02-18,https://www.monster.com.sg/seeker/job-details?...
1,Senior Partner Solutions Architect (Microsoft),Amazon,NaN,permanent,NaN,NaN,Job Description :\r\nJob summary\r\nDESCRIPTIO...,['Internet/E-commerce'],['IT'],['Software Engineer/Programmer'],2022-02-18,https://www.monster.com.sg/seeker/job-details?...
2,IT Technician,Ascend Com Pte. Ltd.,"['24000', '36000']",permanent,"['2', '5']","['Switches', 'Mac', 'Windows 10', 'Cloud Compu...",Responsibilities:\r\nProvide helpdesk support ...,['Other'],['IT'],['Other Software/Hardware/EDP'],2022-02-19,https://www.monster.com.sg/seeker/job-details?...
3,Customer Engineer,Applied Materials South East Asia Pte. Ltd.,"['42000', '84000']",permanent,"['2', '5']","['Scalability', 'Cloud Computing', 'Google Clo...",Key Responsibilities\r\nPerforms all standard ...,['Other'],['Manufacturing/Engineering/R&D'],['Other Production/Engineering/R&D'],2022-02-19,https://www.monster.com.sg/seeker/job-details?...
4,Customer Engineer,Applied Materials South East Asia Pte. Ltd.,"['46800', '93600']",permanent,"['2', '5']","['Scalability', 'Cloud Computing', 'Google Clo...",Has developed specialized skills or is multi-s...,['Other'],['Manufacturing/Engineering/R&D'],['Other Production/Engineering/R&D'],2022-02-19,https://www.monster.com.sg/seeker/job-details?...
...,...,...,...,...,...,...,...,...,...,...,...,...
8410,Application Architect (Classification),Combuilder Pte Ltd,"['108000', '156000']",permanent,"['10', '15']","['Pyspark', 'Scalability', 'Application Develo...",Job Description:\r\nResponsible for overall pl...,['Other'],['IT'],['Other Software/Hardware/EDP'],2022-03-19,https://www.monster.com.sg/seeker/job-details?...
8411,Senior Developer,Vault Personnel Pte. Ltd.,"['66000', '78000']",permanent,"['2', '5']","['Css3', 'Php', '.NET', 'Application Developme...","Job Description:\r\nThe Senior Developer, IT p...",['Other'],['IT'],['Other Software/Hardware/EDP'],2022-03-19,https://www.monster.com.sg/seeker/job-details?...
8412,"Customer Service Exec (East, up to $2500, Gd b...",People Profilers Pte. Ltd.,"['26400', '30000']",permanent,"['0', '2']","['Windows', 'Customer Service Skills', 'Custom...",Location: Paya Lebar\r\nWorking hours: 10am 11...,['Other'],['Customer Service/Call Centre/BPO'],['Other Customer Service/Call Center'],2022-03-19,https://www.monster.com.sg/seeker/job-details?...
8413,"Director, Virtual Banking",Synpulse Singapore Pte. Ltd.,"['120000', '240000']",permanent,"['7', '10']","['Wealth Management', 'Mentoring', 'Quality Co...","As a Director, you will be responsible for man...",['Other'],['Banking'],['Product Manager - Auto/Home/Personal Loan'],2022-03-19,https://www.monster.com.sg/seeker/job-details?...
8414,"Senior IT Manager (Oracle) / Senior Manager, I...",Randstad Pte. Limited,"['120000', '168000']",permanent,"['10', '15']","['Oracle', 'Erp', 'Application Development', '...",About the company\r\nOur Client is a market le...,['Other'],['IT'],['Other Software/Hardware/EDP'],2022-03-19,https://www.monster.com.sg/seeker/job-details?...

In [126]:
# Change filename
all_df.to_csv('All_MonsterSg.csv', index=False)